name: Spellcheck Action For pushed files under the folder .\content\reads

on:
  push:

jobs:
  Reads-Spellcheck:
    name: Spellcheck for reads files
    runs-on: ubuntu-latest

    env:
      temporary-file-name: temp-file.md
      reads-folder: content/reads/
      scripts-folder: .github/scripts/

    steps:
      - name: Clone or Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: List Pushed Files
        id: list-pushed-files
        run: |
          echo "Before commit: ${{ github.event.before }}"
          echo "Current commit: ${{ github.sha }}"
          added_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "$added_files"
          
          # multiline output
          echo "ADDED_FILES<<EOF" >> $GITHUB_OUTPUT
          echo $added_files >> $GITHUB_OUTPUT 
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Get Read File
        id: get-read-file
        run: |
          # Get the list of added files
          added_files="${{ steps.list-pushed-files.outputs.ADDED_FILES }}"
          echo "$added_files"

          if [ -z "$added_files" ]; then
            echo "No pushed files were found!!"
            exit 125
          else
            # Filter files that are in the specific directory
            # '|| true' is used to prevent the workflow from failing if grep returns a non-zero exit code
            filtered_files=$(echo "$added_files" | grep '${{ env.reads-folder }}') || true
            echo "$filtered_files"
            
            # Check the size of the filtered_files array
            if [ -z "$filtered_files" ]; then
              echo "No files found in the '${{ env.reads-folder }}' directory."
              exit 125
            else
              echo "Found files in the '${{ env.reads-folder }}' directory."
              
              # Get the first element if there is more than one
              if [ $(echo "$filtered_files" | wc -l) -gt 1 ]; then
                first_file=$(echo "$filtered_files" | head -n 1)
                echo "Found more than one file. Only the first file will be considered: $first_file"
                echo "PUSHED_READ_FILE=$first_file" >> "$GITHUB_OUTPUT"
              else
                echo "Only one file found, no need to process the first file."
                echo "PUSHED_READ_FILE=$filtered_files" >> "$GITHUB_OUTPUT"
              fi
            fi
          fi

      - name: Create temporary file with content to be checked
        run: |
          echo ${{ steps.get-read-file.outputs.PUSHED_READ_FILE }}
          echo ${{ env.temporary-file-name }}
          ${scripts-folder}copy_sections_to_file.sh ${{ steps.get-read-file.outputs.PUSHED_READ_FILE }} ${{ env.temporary-file-name }}
        shell: bash

      - name: Spellcheck the temporary file
        uses: rojopolis/spellcheck-github-actions@v0
        with:
          source_files: ${{ env.temporary-file-name }}
          task_name: Markdown

      - name: Delete temporary file
        run: |
          ${scripts-folder}delete_file.sh ${{ env.temporary-file-name }}
        shell: bash