name: Spellcheck Action

on:
  push:

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest

    steps:
      - name: Clone or Checkout repository
        uses: actions/checkout@v4

      - uses: rojopolis/spellcheck-github-actions@v0
        name: Spellcheck
        with:
          task_name: Markdown